language: groovy
jdk:
  - oraclejdk8
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN=bffc2243-7c46-48ca-a029-7993e37f4582
